# <number> = positive number made up from digits 0 to 9
# <time> = <number> <unit>
#        | "never"
# <unit> = "s" (seconds)
#        | "m" (minutes)
#        | "h" (hours)
#        | "d" (days)


# <time> after which the soul can be collected by anyone
soul-free-after: 1h
# <time> after which the soul disappears
soul-fades-after: never

# How the souls behave in PvP. Possible values:
#   normal: no change
#   disabled: souls are not created in PvP, items and XP drops like in vanilla Minecraft
#   free: created souls are immediately free and can be collected by anyone
pvp-behavior: normal

# <percent> = <number> "%"
# <xp-per-level> = <number>

# <percent> of experience points retained by souls
# OR <xp-per-level> to retain by soul. Vanilla behavior is 7 xp-per-level.
# Soul will never retain more xp than the player has collected.
retained-xp: 90%

# Souls will not be placed directly where the player has died, but at the last
# player's location which is considered safe (unless it is too far away).
# For example, when player falls to their death, their soul will be placed at the ledge from which they fell.
# Similarly for falling into lava.
smart-soul-placement: true

# EXPERIMENTAL: These entities will drop their items and XP as an soul
# instead of dropping them on the ground. Entries must match names of enum constants from
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html perfectly, even the letter case!
animals-with-souls: []

# Sound played when collecting XP from a soul
sound-soul-collect-xp: entity.experience_orb.pickup
# Sound played when collecting items from a soul
sound-soul-collect-item: item.trident.return
# Sound played when everything in the soul has been collected and the soul disappears
sound-soul-depleted: entity.generic.extinguish_fire
# Sound played by nearby souls to eligible players, to help them better find the soul
sound-soul-calling: block.beacon.ambient
# Volume with which the soul is calling. Values above 1 only affect distance.
volume-soul-calling: 16
# Sound played to dying players that drop a soul
# NOTE FOR 1.13 USERS: This sound exists only since 1.14, suggested replacement is: block.beacon.power_select
sound-soul-dropped: block.bell.resonate

# Color: HTML-like color in RRGGBB format (without leading #).
# Somewhat nice color picker is available here: https://www.colorcodehex.com/html-color-picker.html
# For example:
#   FF0000 - pure red
#   00FF00 - pure green
#   0000FF - pure blue
#   71B05F - sickly green
# Color of the soul when it holds items (default: pure white)
color-soul-items: FFFFFF
# Color of the soul when it holds XP (default: pure aqua/cyan)
color-soul-xp: 00FFFF
# Color of the soul when it disappears (default: pure yellow)
color-soul-gone: FFFF00

# Text on a button to free the soul (Set to empty to disable this functionality)
text-free-my-soul: "Free my soul"
# Text displayed as a tooltip on button to free player's soul (Set to empty to disable the tooltip)
text-free-my-soul-tooltip: "Allows other players to collect the soul immediately"

# <time> How frequently should auto-save of the soul database occur (only if modified and not more frequently than once per second)
# never      = saving happens only on server restart (not generally recommended, unless you are sure that your server is stable)
# otherwise  = plugin will attempt to save periodically, after this time interval passes
#              0s is recommended for servers with infrequent deaths
#              1m or 5m might be sensible values for large servers
auto-save: 0s